name: Briefcase Build

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9].*'
  workflow_dispatch:

jobs:
  briefcase:
    name: Bundle on ${{ matrix.platform }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python libs
        run: |
          python -m pip install --upgrade pip
          python -m pip install briefcase

      - name: Create and Build Bundle
        run: |
          briefcase create
          briefcase build

      - name: Package Mac
        if: runner.os == 'macOS'
        run: briefcase package --adhoc-sign

      - name: Package Windows / Linux
        run: briefcase package

      - name: Upload Artifact for Linux
        uses: actions/upload-artifact@v2
        if: runner.os == 'Linux'
        with:
          name: filemonitor-${{ github.ref_name }}-${{ matrix.platform }}.AppImage
          path: '**/*.AppImage'

      - name: Upload Artifact for MacOS
        uses: actions/upload-artifact@v2
        if: runner.os == 'MacOS'
        with:
          name: filemonitor-${{ github.ref_name }}-${{ matrix.platform }}.dmg
          path: '**/*.dmg'

      - name: Upload Artifact for Windows
        uses: actions/upload-artifact@v2
        if: runner.os == 'Windows'
        with:
          name: filemonitor-${{ github.ref_name }}-${{ matrix.platform }}.msi
          path: '**/*.msi'

      - name: Release nightly
        uses: softprops/action-gh-release@v1
        if: runner.os == 'Windows'
        with:
          prerelease: true
          name: nightly
          tag_name: nightly
          files: filemonitor-main-windows-latest.msi
          fail_on_unmatched_files: true
